CC      = gcc
CFLAGS  = -g
all: parta partb partc

parta: p1a.c
	$(CC) p1a.c $(CFLAGS) -o p1a 

partb: p1b.c
	$(CC) p1b.c $(CFLAGS) -o p1b

partc: p1c.c
	$(CC) p1c.c $(CFLAGS) -o p1c

clean:
	rm -f p1a p1b p1c
